# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Works\PythonProjects\NLPLab1\Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, Qt
from PyQt5.QtGui import QMouseEvent
from PyQt5.QtWidgets import QTextEdit

#inherit from QTextEdit to use clicked event
class MyTextEdit(QTextEdit):
    clicked = pyqtSignal()
    def mouseReleaseEvent(self, QMouseEvent):
        if QMouseEvent.button()==Qt.LeftButton:
            self.clicked.emit()

class Ui_Form(object):
# ui design
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(600, 500)

# label design (for displaying emoji)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 0, 300, 300))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setPointSize(100)
        self.label.setFont(font)

# label design(for displaying emotion text)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 300, 200, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
# textEdit design(for user to input sentence for prediction)
        self.textEdit = MyTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(100, 350, 400, 60))
        self.textEdit.setObjectName("textEdit")
# Button design(click this button to check result)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 450, 120, 30))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
# dont know what it is, still learning pyQT5
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
# set up the initial text for each UI element
        Form.setWindowTitle(_translate("Form", "Sentiment Classification app"))
        self.textEdit.setText(_translate("Form","Please insert one sentence and click button below to check result"))
        self.label.setText(_translate("Form", "🤔"))
        self.label_2.setText(_translate("Form", "emotion"))
        self.pushButton.setText(_translate("Form", "Check"))
